### ISSUE TITLE
NameError: name 'get_ipython' is not defined

### ISSUE THREAD

**Issue by pkmantra** [Dharun/TensorPy#11]
Traceback (most recent call last):
  File "numplate_recognition_detection.py", line 13, in <module>
    get_ipython().magic('matplotlib inline')
NameError: name 'get_ipython' is not defined

I have received above error.
How to run it properly?

**Comment by AmbarishGK** [comment]
Did you try it with anaconda?

**Comment by tabarkarajab** [comment]
use ipython numplate_recognition_detection.py
