### ISSUE TITLE
No such file / folder training\object-detection.pbtxt

### ISSUE THREAD

**Issue by sarc007** [Dharun/TensorPy#13]
Line 34 in your code : `label_map = label_map_util.load_labelmap(PATH_TO_LABELS)`
No such file / folder training\object-detection.pbtxt ?
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: training\object-detection.pbtxt : The system cannot find the file specified.
; No such file or directory

**Comment by Dharun** [comment]
item {
  id: 1
  name: 'numplate'
}

please save the above snip as object-detection.pbtxt
