### ISSUE TITLE
Missing file in Proto or Util

### ISSUE THREAD

**Issue by jigarvira** [Dharun/TensorPy#14]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-3ffb8ec70902> in <module>
      2 sys.path.append("/Users/jivira/Tensorflow-License-Plate-Detection-master/object_detection")
      3 
----> 4 from utils import label_map_util
      5 from utils import visualization_utils as vis_util
      6 

~/Tensorflow-License-Plate-Detection-master/object_detection/utils/label_map_util.py in <module>
     24 import tensorflow as tf
     25 from google.protobuf import text_format
---> 26 from object_detection.protos import string_int_label_map_pb2
     27 
     28 

ImportError: cannot import name 'string_int_label_map_pb2'

Can you please help me in this....

**Comment by veeri** [comment]
download the models from https://github.com/tensorflow/models and import utils 
in my case 

sys.path.append("D:\\FRS_Project\\tensorflow-models\\models\\research")

from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util
hopes it will work
