### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection

### ISSUE THREAD

**Issue by MatusGaal** [Dharun/TensorPy#16]
Hi, I downloaded repository and tried to run numplate_recognition_detection, I'm running it with anaconda IPython 7.8.0. First I got error message: "UnknownBackend: No event loop integration for 'inline'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx". According to tensorflow discussion I replaced matplotlib inline for matplotlib tk. but then I got error message: ModuleNotFoundError: No module named 'utils'. I downloaded utils file from previous issue but than this showed up: ModuleNotFoundError: No module named 'object_detection_evaluation'. Any idea on what am I doing wrong? (note, first time using IPython O:) )

**Comment by arnodorian-r** [comment]
download tensorflow object detection api and compile the protobuf files.
then copy the object_detection folder from models/research/object detection to this project folder.

then change this line from code :

from utils import label_map_util
from utils import visualization_utils as vis_util

to this :

from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util
