### ISSUE TITLE
EMPTY PACKAGE OR MODULE

### ISSUE THREAD

**Issue by SKTEE-2020** [Dharun/TensorPy#18]
HI, I am a new student researcher in python, I downloaded your projects and installed all the dependables but on running  your code I got error "ModuleNotFoundError: No module named 'object_detection.utils'". I went and pip install utils and tried again but same error. i checked in your project and saw object_detedtion as a folder (more like a package) and it is literally empty. please guide me on how to fix this.

**Comment by Dharun** [comment]
[API](https://github.com/tensorflow/models/tree/master/research/object_detection) Please download from here.
