### ISSUE TITLE
NameError: name 'get_ipython' is not defined

### ISSUE THREAD

**Issue by innoveexperience** [Dharun/TensorPy#19]
/Tensorflow-License-Plate-Detection-master/numplate_recognition_detection.py", line 13, in <module>
    get_ipython().magic('matplotlib inline')

where can get_ipython be defined?
the file has not been changed, I just installed the packages.
greetings!

**Comment by Usama323** [comment]
I have solved the same issue by adding # at the start of this line (i.e comment this line)
