### ISSUE TITLE
Tesseract model

### ISSUE THREAD

**Issue by huseinzol05** [Dharun/TensorPy#2]
```python
pytesseract.tesseract_cmd = '/home/tensorflow-cuda/dharun_custom/models/research/object_detection/tessdata/'
```

I don't find this folder inside this repository, maybe you can refactor this repository to make it more understandable? thank you!

**Comment by Dharun** [comment]
Hi, It's simple. Install Tesseract engine. Point the location of tessdata folder in the command.
