### ISSUE TITLE
Training for new Country

### ISSUE THREAD

**Issue by alucard079** [Dharun/TensorPy#7]
Thanks for this repository, can I use this to train my own model, for example I have two model for our country and train it using this?

Will this program be able to make it real time using IP Camera?

**Comment by sujit25** [comment]
@alucard079 : you can use Opencv's VideoCapture class where IP Camera's ip can be passed as argument and its frames can be captured. Once frames are captured, you can pass them downstream to rest of pipeline for prediction.

**Comment by akniloy6** [comment]
for ip camera guidance you can follow this:
https://github.com/AKNiloy/Tensorflow-custom-object-detection-with-ip-camera
