### ISSUE TITLE
No 'training\object-detection.pbtxt' file in repository

### ISSUE THREAD

**Issue by AbhishekMuddebihal** [Dharun/TensorPy#8]
Hello, 
       Thanks for this repository, can you add 'training\object-detection.pbtxt' file to this repository.
      This file is required to run this project, and file is missing from repository.

**Comment by Dharun** [comment]
item {
id: 1
name: 'numplate'
}


@AbhishekMuddebihal Save the above code as **object-detection.pbtxt**
